// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewFile() {
  return window['go']['main']['App']['NewFile']();
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function RunCode(arg1) {
  return window['go']['main']['App']['RunCode'](arg1);
}

export function RunCodeInCMD(arg1) {
  return window['go']['main']['App']['RunCodeInCMD'](arg1);
}

export function SaveFile(arg1) {
  return window['go']['main']['App']['SaveFile'](arg1);
}

export function SaveFileAs(arg1) {
  return window['go']['main']['App']['SaveFileAs'](arg1);
}
