// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function NewFile():Promise<void>;

export function OpenFile():Promise<string>;

export function RunCode(arg1:string):Promise<string>;

export function RunCodeInCMD(arg1:string):Promise<string>;

export function SaveFile(arg1:string):Promise<string>;

export function SaveFileAs(arg1:string):Promise<string>;
